wandb_version: 1

batch_size:
  value: 4
d_k:
  value: 32
data:
  value: data/Breakfast/
device:
  value: cuda
dropout:
  value: 0.1
epochs:
  value: 50
learning_rate:
  value: 0.0001
n_head:
  value: 8
n_layers:
  value: 3
num_mix_components:
  value: 4
smooth:
  value: 0
