wandb_version: 1

batch_size:
  value: 4
d_k:
  value: 64
d_model:
  value: 64
data:
  value: data/Breakfast/
device:
  value: cuda
dropout:
  value: 0.1
epochs:
  value: 50
learning_rate:
  value: 2.5e-05
n_head:
  value: 4
n_layers:
  value: 4
num_mix_components:
  value: 16
smooth:
  value: 0
