wandb_version: 1

batch_size:
  value: 4
d_k:
  value: 32
d_model:
  value: 256
data:
  value: data/Breakfast/
device:
  value: cuda
dropout:
  value: 0.1
epochs:
  value: 35
learning_rate:
  value: 7.112752691632066e-05
n_head:
  value: 4
n_layers:
  value: 4
num_mix_components:
  value: 16
smooth:
  value: 0
