wandb_version: 1

activation:
  value: softplus
batch_size:
  value: 4
d_inner:
  value: 256
d_k:
  value: 4
d_model:
  value: 64
d_rnn:
  value: 128
d_v:
  value: 4
dropout:
  value: 1
epochs:
  value: 100
learning_rate:
  value: 1.0e-05
n_layer:
  value: 4
