wandb_version: 1

activation:
  value: softplus
batch_size:
  value: 4
d_k:
  value: 128
d_model:
  value: 512
d_rnn:
  value: 128
data:
  value: data/Breakfast/
device:
  value: cuda
dropout:
  value: 0.1
epochs:
  value: 35
learning_rate:
  value: 0.0001
n_head:
  value: 4
n_layers:
  value: 4
smooth:
  value: 0
