wandb_version: 1

activation:
  value: default
batch_size:
  value: 4
d_k:
  value: 64
d_model:
  value: 512
d_rnn:
  value: 0
data:
  value: data/Breakfast/
device:
  value: cuda
dropout:
  value: 0.1
epochs:
  value: 50
learning_rate:
  value: 0.01
n_head:
  value: 4
n_layers:
  value: 4
smooth:
  value: 0.1
