wandb_version: 1

batch_size:
  value: 4
d_k:
  value: 64
d_model:
  value: 512
data:
  value: data/Breakfast/
device:
  value: cuda
dropout:
  value: 0.1
epochs:
  value: 70
learning_rate:
  value: 0.00061842868782978
n_head:
  value: 4
n_layers:
  value: 4
num_mix_components:
  value: 24
smooth:
  value: 0
