wandb_version: 1

batch_size:
  value: 4
d_k:
  value: 128
d_model:
  value: 256
data:
  value: data/Breakfast/
device:
  value: cuda
dropout:
  value: 0.1
epochs:
  value: 70
learning_rate:
  value: 0.0008283666766661546
n_head:
  value: 4
n_layers:
  value: 4
num_mix_components:
  value: 24
smooth:
  value: 0
