wandb_version: 1

batch_size:
  value: 4
d_k:
  value: 64
d_model:
  value: 256
data:
  value: data/Breakfast/
device:
  value: cuda
dropout:
  value: 0.1
epochs:
  value: 70
learning_rate:
  value: 5.06976802867265e-05
n_head:
  value: 4
n_layers:
  value: 4
num_mix_components:
  value: 32
smooth:
  value: 0
