wandb_version: 1

batch_size:
  value: 4
d_k:
  value: 32
d_model:
  value: 512
data:
  value: data/Breakfast/
device:
  value: cuda
dropout:
  value: 0.1
epochs:
  value: 70
learning_rate:
  value: 0.0006459838937514429
n_head:
  value: 4
n_layers:
  value: 4
num_mix_components:
  value: 45
smooth:
  value: 0
