wandb_version: 1

activation:
  desc: null
  value: softplus
batch_size:
  desc: null
  value: 4
d_k:
  desc: null
  value: 128
d_model:
  desc: null
  value: 256
d_rnn:
  desc: null
  value: 0
data:
  desc: null
  value: data/Breakfast/
device:
  desc: null
  value: cuda
dropout:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 35
learning_rate:
  desc: null
  value: 0.0001
n_head:
  desc: null
  value: 4
n_layers:
  desc: null
  value: 4
smooth:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705687819.899112
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.16
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
