wandb_version: 1

activation:
  value: softplus
batch_size:
  value: 4
d_inner:
  value: 256
d_k:
  value: 4
d_model:
  value: 64
d_rnn:
  value: 0
d_v:
  value: 4
dropout:
  value: 0
epochs:
  value: 100
learning_rate:
  value: 0.01
n_layer:
  value: 4
