wandb_version: 1

activation:
  value: default
batch_size:
  value: 4
d_k:
  value: 512
d_model:
  value: 256
d_rnn:
  value: 128
data:
  value: data/Breakfast/
device:
  value: cuda
dropout:
  value: 0.1
epochs:
  value: 70
learning_rate:
  value: 5.0e-05
n_head:
  value: 4
n_layers:
  value: 4
smooth:
  value: 0
